### ISSUE TITLE
意见

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_remove_bg#1]
是否添加消息回复可以触发

**Comment by Ikaros-521** [comment]
计划推进中

**Comment by Ikaros-521** [comment]
v0.1.0版本发布
# 0.1.0

- 修改原 remove_bg命令至 自定义去背景 功能（采用shell cmd的形式）。
- 原 rm_bg 和 去背景 命令，增加可以直接回复图片进行处理。
